# -*- coding: utf-8 -*-
"""trainers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kEBoS_rfngQYEzWi3KThlDPAeiXDPipI
"""

# Save the checkpoint in the /output folder
# Saves model - quora_model_best.hdf5
from keras.callbacks import ModelCheckpoint
from models.QuoraModel import QuoraModel
import pickle
import os
# filepath = "drive/My Drive/datasets/iamplus/trained_models/quora_model_best.hdf5"
#os.getcwd()
#filepath = "/Users/rahulm/Desktop/LEARN/Assignments/Iamplus/project/model/trained_models/quora_model_best.hdf5"

# Filepath to save checkpoint models
filepath = os.path.join(os.getcwd(),'model/trained_models/quora_model_best.hdf5')

with open(os.path.join(os.getcwd(),'models/files/training_X.pickle'),'rb') as f:
    training_X = pickle.load(f)
with open(os.path.join(os.getcwd(),'models/files/val_X_encoded.pickle'),'rb') as f:
    val_X_encoded = pickle.load(f)
with open(os.path.join(os.getcwd(),'models/files/val_y.pickle'),'rb') as f:
    val_y = pickle.load(f)
with open(os.path.join(os.getcwd(),'models/files/test_X_encoded.pickle'),'rb') as f:
    test_X_encoded = pickle.load(f)
with open(os.path.join(os.getcwd(),'models/files/train_y.pickle'),'rb') as f:
    train_y = pickle.load(f)



class Model_Trainer():
  def __init__(self,training_X,train_Y,val_X_encoded,val_y):
    # Keep only a single checkpoint, the best over test accuracy.
    self.checkpoint = ModelCheckpoint(filepath,
                            monitor='val_acc',
                            verbose=1,
                            save_best_only=True, # Save best checkpoints
                            mode='max')

  def train(self,model):
    history = self.model.fit(training_X,train_y,
                             epochs=2,
                             batch_size=512,
                             validation_data = (val_X_encoded,val_y),
                             callbacks=[self.checkpoint])
    #self.model.save('../trained_models/model_quora1.h5')
